language: julia
os:
  - windows
  - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("DiscreteDifferentialGeometry")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
